python: 2.7
script:
  - pip install --user -r requirements.txt
  - python -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
