python: 2.7
script:
  - pip install --user -r requirements.txt
  - python -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
